import type { Book, BookAccess, Transaction, User } from "./types";

export const allBooks: Book[] = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    authorId: "author_1",
    price: 14.99,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
    category: "Fiction",
    coverType: "Paperback",
    stock: 25,
    reorderPoint: 5,
    publishedAt: new Date('2020-08-01'),
    sales: 150,
    revenue: 2248.5,
    averageRating: 4.2,
    totalReviews: 89,
  },
  {
    id: "2",
    title: "Project Hail Mary",
    author: "Andy Weir",
    authorId: "author_2",
    price: 18.5,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.",
    category: "Science",
    coverType: "Hardcover",
    stock: 15,
    reorderPoint: 3,
    publishedAt: new Date('2021-05-04'),
    sales: 230,
    revenue: 4255.0,
    averageRating: 4.6,
    totalReviews: 167,
  },
  {
    id: "3",
    title: "Dune",
    author: "Frank Herbert",
    authorId: "author_3",
    price: 12.0,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange.",
    category: "Fantasy",
    coverType: "Paperback",
    stock: 30,
    reorderPoint: 8,
    publishedAt: new Date('1965-10-01'),
    sales: 890,
    revenue: 10680.0,
    averageRating: 4.8,
    totalReviews: 542,
  },
  {
    id: "4",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    authorId: "author_4",
    price: 22.0,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "A groundbreaking narrative of humanity's creation and evolution—a #1 international bestseller that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be 'human.'",
    category: "History",
    coverType: "Hardcover",
    stock: 20,
    reorderPoint: 4,
    publishedAt: new Date('2011-09-04'),
    sales: 675,
    revenue: 14850.0,
    averageRating: 4.4,
    totalReviews: 398,
  },
  {
    id: "5",
    title: "The Four Winds",
    author: "Kristin Hannah",
    authorId: "author_5",
    price: 16.99,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "An epic novel of love and heroism and hope, set against the backdrop of one of America's most defining eras—the Great Depression.",
    category: "Fiction",
    coverType: "Paperback",
    stock: 18,
    reorderPoint: 5,
    publishedAt: new Date('2021-02-02'),
    sales: 334,
    revenue: 5673.66,
    averageRating: 4.3,
    totalReviews: 245,
  },
  {
    id: "6",
    title: "Educated: A Memoir",
    author: "Tara Westover",
    authorId: "author_6",
    price: 17.99,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    category: "Biography",
    coverType: "Hardcover",
    stock: 12,
    reorderPoint: 3,
    publishedAt: new Date('2018-02-20'),
    sales: 445,
    revenue: 8005.55,
    averageRating: 4.5,
    totalReviews: 312,
  },
  {
    id: "7",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    authorId: "author_7",
    price: 11.5,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "A tale of gods, kings, immortal fame, and the human heart, The Song of Achilles is a dazzling literary feat that brilliantly reimagines Homer's enduring masterwork, The Iliad.",
    category: "Fantasy",
    coverType: "Paperback",
    stock: 40,
    reorderPoint: 10,
    publishedAt: new Date('2011-09-20'),
    sales: 567,
    revenue: 6520.5,
    averageRating: 4.7,
    totalReviews: 423,
  },
  {
    id: "8",
    title: "Atomic Habits",
    author: "James Clear",
    authorId: "author_8",
    price: 20.0,
    imageUrl: "https://placehold.co/400x600.png",
    description:
      "An easy and proven way to build good habits and break bad ones. Tiny changes, remarkable results.",
    category: "Non-Fiction",
    coverType: "Hardcover",
    stock: 50,
    reorderPoint: 15,
    publishedAt: new Date('2018-10-16'),
    sales: 1234,
    revenue: 24680.0,
    averageRating: 4.6,
    totalReviews: 876,
  },
];

export const bookCategories = [
  "All",
  "Fiction",
  "Non-Fiction",
  "Science",
  "Fantasy",
  "History",
  "Biography"
];

export const userBookAccess: BookAccess[] = [
  { userId: 'reader1', bookId: '2', purchaseDate: new Date() },
  { userId: 'reader1', bookId: '7', purchaseDate: new Date() },
];

export const transactions: Transaction[] = [
    { id: 'txn1', userId: 'reader1', bookId: '2', quantity: 1, amount: 18.50, status: 'success', createdAt: new Date() },
    { id: 'txn2', userId: 'reader1', bookId: '7', quantity: 1, amount: 11.50, status: 'success', createdAt: new Date() },
];